sonar.projectKey=donovangong_ca22
sonar.organization=donovangong
sonar.projectName=CA2 Order Inventory
sonar.projectVersion=1.0

sonar.sources=services,resources
sonar.tests=test

sonar.exclusions=**/node_modules/**,**/.git/**,**/coverage/**,**/dist/**,**/build/**
sonar.test.inclusions=test/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/functional-coverage/lcov.info,coverage/api-coverage/lcov.info,coverage/integration-coverage/lcov.info
sonar.coverage.exclusions=**/server.js,resources/**,test/**
sonar.sourceEncoding=UTF-8
