apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: product-service-scaledobject
  namespace: ca2
spec:
  scaleTargetRef:
    name: product-service
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 30
  cooldownPeriod: 60
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
