name: functional-test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  functional-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Run functional tests
        run: |
          node test/functional/run-functional-tests.js
